namespace AdventOfCode.Tests.Puzzles;

public class Puzzle07Tests
{
    private readonly Puzzle07 _puzzle;

    public Puzzle07Tests()
    {
        _puzzle = new Puzzle07();
    }

    [Fact]
    public void SolvePart1()
    {
        var result = _puzzle.SolvePart1();
        result.Should().Be(1687);
    }

    [Fact(Skip = "Not yet implemented")]
    public void SolvePart2()
    {
        var result = _puzzle.SolvePart2();
        result.Should().Be(0);
    }

    [Fact]
    public void TestPart1WithExampleInput()
    {
        _puzzle.SetTestInput("""
                             .......S.......
                             ...............
                             .......^.......
                             ...............
                             ......^.^......
                             ...............
                             .....^.^.^.....
                             ...............
                             ....^.^...^....
                             ...............
                             ...^.^...^.^...
                             ...............
                             ..^...^.....^..
                             ...............
                             .^.^.^.^.^...^.
                             ...............
                             """);
        var result = _puzzle.SolvePart1();
        result.Should().Be(21);
    }

    [Fact(Skip = "Wrong result")]
    public void TestPart2WithExampleInput()
    {
        _puzzle.SetTestInput("""
                             .......S.......
                             ...............
                             .......^.......
                             ...............
                             ......^.^......
                             ...............
                             .....^.^.^.....
                             ...............
                             ....^.^...^....
                             ...............
                             ...^.^...^.^...
                             ...............
                             ..^...^.....^..
                             ...............
                             .^.^.^.^.^...^.
                             ...............
                             """);
        var result = _puzzle.SolvePart2();
        result.Should().Be(40);
        // We currently get only 24...
        //
        // The debug output from the example input looks like the following,
        // illustrating the number of timelines at every single point:
        //
        //         .......1.......
        //         .......1.......
        //         ......1.1......
        //         ......1.1......
        //         .....1.2.1.....
        //         .....1.2.1.....
        //         ....1.3.3.1....
        //         ....1.3.3.1....
        //         ...1.4.331.1...
        //         ...1.4.331.1...
        //         ..1.5.434.2.1..
        //         ..1.5.434.2.1..
        //         .1.154.44.21.1.
        //         .1.154.44.21.1.
        //         1.2.5.8.4.211.1  => Sum: 24
    }
}
